// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irbjnfzdjxocrqjbktbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyYmpuZnpkanhvY3JxamJrdGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzI2NTAsImV4cCI6MjA3MTIwODY1MH0.gJE0hiPfT-ZNi-4-yqovtpG4ECppbUUWmmuuTku5yxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});